name: Run Julia Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-julia:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up auth.toml
        run: |

      - name: Pull and run Julia container
        uses: addnab/docker-run-action@v3
        with:
          image: julia:1.9
          options: --rm
          run: |
            mkdir -p ~/.julia/servers/pkg.juliahub.com
            echo ${{ secrets.AUTH_TOML }}| base64 -d > ~/.julia/servers/pkg.juliahub.com/auth.toml
            julia -e 'print(VERSION)'
            export JULIA_PKG_SERVER=https://pkg.juliahub.com
            julia -e 'using Pkg; Pkg.add("PkgAuthentication");using PkgAuthentication;PkgAuthentication.install()'          
            
