name: Run Julia Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env: 
  JULIA_PKG_SERVER: 'https://pkg.juliahub.com'
jobs:
  run-julia:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up auth.toml
        run: |
          mkdir -p ~/.julia/servers/juliahub.com
          echo "${{ secrets.auth_toml }}" > ~/.julia/servers/juliahub.com/auth.toml
        
      - name: Pull and run Julia container
        uses: addnab/docker-run-action@v3
        with:
          image: julia:1.9  # Specify the Julia version you want
          options: --rm  # Remove the container when done
          run: |
            julia -e 'print(VERSION)'
            julia -e 'using Pkg; Pkg.add("JuliaHub");JuliaHub.authenticate()'

            
